### ISSUE TITLE
problems with symfony's ApcuAdapter 

### ISSUE THREAD

**Issue by Joduai** [mikespub-org/rvolz-BicBucStriim#3]
After years of using BBS without updating I had to switch to another domain with all my playground, thus I thought I'd update some things by the way. After setting up everything and resolving some problems with switching to php 8.3 I did get a blank page when visiting the library. I didn't know where to start as enabling error reporting was a pain in the ass. But once I got to see the php errors it turned out that I had problems with symfony's cache adapter. 
By default it uses ApcuAdapter which I don't even know how to enable on shared webhosting, even with ssh access.  
As symfony offers many cache adapters and I was too lazy to mess with with redis or memcache I just switched to FilesystemAdapter.  

I thought I just let you know that it may be a good approach to check first if apcu is available, and use the filesystemadapter as a fallback. Eventually adding some choices in config file.

**Comment by mikespub** [comment]
Thanks @Joduai - as far as I heard the php-apcu module is no longer enabled by default for PHP 8.3 in some Linux distributions (for whatever reason), but I'm sure your web hoster should be able to re-activate it for you.

Otherwise as you say the filesystem adapter would be a good fallback. Thanks - I'll keep it in mind for any future updates :-)

**Comment by mikespub** [comment]
Fixed in [release 3.4.2](https://github.com/mikespub-org/rvolz-BicBucStriim/releases/tag/v3.4.2)
