### ISSUE TITLE
Dark Default Theme

### ISSUE THREAD

**Issue by sohanev** [mikespub-org/rvolz-BicBucStriim#8]
If possible, add a dark default theme. I made changes to jquery.mobile-git.min. I think it would look nice. The question is how to make it possible to choose a color theme.

[jquery.mobile-git.min.css.zip](https://github.com/user-attachments/files/17711759/jquery.mobile-git.min.css.zip)

![Screenshot_20241112_085334_Chrome](https://github.com/user-attachments/assets/1d24f122-183b-4f70-8183-ec774b1ea592)

**Comment by mikespub** [comment]
BBS has configuration settings + a database where all kinds of settings could be stored - including themes if we have them.

But I am *not* the right person to create/adapt front-end themes, styles, templates etc. This is what happens when I try it: https://thecodinglove.com/when-i-try-to-modify-a-css-stylesheet :-)

So you would need someone else to create it, and submit a PR with the necessary changes on the front-end side.

Once I have that, I can change the back-end code to allow people to choose a theme etc.

**Comment by sohanev** [comment]
Done!) Made a ready template. You can choose in the configuration menu.

darksoha template
Installation:
Unzip the contents of the archive to the root folder bbs

[darksoha.zip](https://github.com/user-attachments/files/17719003/darksoha.zip)

After installation, it is advisable to force refresh the page shift+F5

**Comment by mikespub** [comment]
Wow - ok, I wasn't expecting a full new template set, but that works too :-)

I've refreshed your templates with the latest changes, removed the duplicate javascript library, and basically only kept the style changes for now - that way we start from the same point. I could add some settings to change the footer dynamically too if you're interested.

And if you want to tweak your set of templates later and send me an update on those, that's fine by me too - as long as they're re-usable by somebody else of course ;-)

Thanks

**Comment by mikespub** [comment]
See [release 3.6.3](https://github.com/mikespub-org/rvolz-BicBucStriim/releases/tag/v3.6.3)

**Comment by sohanev** [comment]
My experiments:
added a table view for books

Problems:
The button to change the display mode of books does not work without reloading the page

[https://imgur.com/a/QhxRsot](url)
